# -*-makefile-*-
#
# name & version of the corpus

CORPUS  = Europarl
VERSION = v8syn

SKIP_TOKENIZATION := 1


# with SRCHTML you can define some extra HTML code that will be placed just
# after the name of the sub-corpus
# EXTRAHTML is code which will be put just after the 'Download' header

SRCHTML = This is a collection of automatically translated documents from English Europarl v8 into other languages using GPT-4o. This release includes translations from English into Basque (eu), Scottish Gaelic (gd), Icelandic (is), Georgian (ka), Macedonian (mk), Somali (so) and Ukrainian (uk). The translated files are also linked to other official languages in the Europarl corpus v8 by pivoting the links through the English documents used as input. The translations of the languages listed above are produced by prompting <a href="https://openai.com/index/gpt-4o-system-card/">GPT-4o provided by OpenAI</a>. When downloading the data you confirm that you agree with the terms and conditions as defined by the <a href="https://openai.com/policies/usage-policies/">usage policies of OpenAI</a>.
